language: ruby
script:
- ruby -e 'puts ENV["MY_ENV"] || "Hello, World!"'
before_deploy:
  # check uri gem version
  # - gem list uri
  # update uri gem
  # - gem update uri
deploy:
  # provider: pages:git
  provider: pages
  token: "$GITHUB_TOKEN"
